---
version: "2"
checks:
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  method-complexity:
    enabled: false
  nested-control-flow:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
