---
version: "2"
checks:
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  method-complexity:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false
