---
fixtures:
  # Lazy way to get all the code (puppet modules and otherwise) onto the test
  # hosts.  Within the tests, we'll relocate and fix permissions appropriately.
  repositories:
    simpkv: https://github.com/simp/pupmod-simp-simpkv.git
    # Puppet modules
    # - Older version of simplib will be cloned in the test, as fixtures code
    #   can only handle one version per URL
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git

    # To set ClientAlive* settings for sshd_config
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh.git

    # For `simp config`
    augeasproviders_grub: https://github.com/simp/augeasproviders_grub.git

    # Other assets
    # - WARNING: rsync data does not remain intact through the fixtures copy
    #   process...Required empty directories are removed!
    adapter: https://github.com/simp/simp-adapter.git
    environment_skeleton: https://github.com/simp/simp-environment-skeleton.git
    rsync_data: https://github.com/simp/simp-rsync-skeleton.git
    simp_selinux_policy: https://github.com/simp/simp-selinux-policy.git

  symlinks:
    # simp cli
    rubygem_simp_cli: "#{source_dir}"

    # test module that uses simplib::passgen
    passgen_test:   "#{File.join(source_dir, 'spec', 'support', 'modules', 'passgen_test')}"

    # test module that uses libkv::xxx
    kv_test:   "#{File.join(source_dir, 'spec', 'support', 'modules', 'kv_test')}"

