---
fixtures:
  # Lazy way to get all the code (puppt modules and otherwise) onto the test
  # hosts.  Within the tests, we'll relocate and fix permissions appropriately.
  repositories:
    simpkv: https://github.com/simp/pupmod-simp-simpkv
    # Puppet modules
    # - Older version of simplib will be cloned in the test, as fixtures code
    #   can only handle one version per URL
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib

    # To set ClientAlive* settings for sshd_config
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders_ssh: https://github.com/simp/augeasproviders_ssh

    # Other assets
    # - WARNING: rsync data does not remain intact through the fixtures copy
    #   process...Required empty directories are removed!
    environment_skeleton: https://github.com/simp/simp-environment-skeleton
    rsync_data: https://github.com/simp/simp-rsync-skeleton
    simp_selinux_policy: https://github.com/simp/simp-selinux-policy

  symlinks:
    # simp cli
    rubygem_simp_cli: "#{source_dir}"

    # test module that uses simplib::passgen
    passgen_test:   "#{File.join(source_dir, 'spec', 'support', 'modules', 'passgen_test')}"

    # test module that uses libkv::xxx
    kv_test:   "#{File.join(source_dir, 'spec', 'support', 'modules', 'kv_test')}"

