<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el7:
    roles:
      - default
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  vagrant_memsize: 4608
  vagrant_cpus: 2
  ssh:
    keepalive: true
    keepalive_interval: 1
  synced_folder : disabled
  type: aio

<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
