<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el6:
    roles:
      - server
      - default
      - master
      - client
    platform: el-6-x86_64
    box: centos/6
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 4608
    vagrant_cpus: 2

  el7:
    roles:
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>
    vagrant_memsize: 4608
    vagrant_cpus: 2

CONFIG:
  log_level: verbose
  synced_folder : disabled
  type: aio

<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
