# Run checks and test matrix on Pull Requests
# ==============================================================================
#
# The testing matrix considers ruby/puppet versions supported by SIMP and PE:
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby    EOL
# SIMP 6.4      5.5      2.40    TBD
# PE 2018.1     5.5      2.40    2021-01 (LTS overlap)
# PE 2019.8     6.18     2.5     2022-12 (LTS)
#
# https://puppet.com/docs/pe/2018.1/component_versions_in_recent_pe_releases.html
# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ==============================================================================
#
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
#

name: PR Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]

env:
  PUPPET_VERSION: '~> 6'

jobs:
  ruby-style:
    if: false # TODO Modules will need: rubocop in Gemfile, .rubocop.yml
    name: 'Ruby Style (experimental)'
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: "Install Ruby ${{matrix.puppet.ruby_version}}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - run: |
          bundle show
          bundle exec rake rubocop

  releng-checks:
    name: 'RELENG checks'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Ruby ${{matrix.puppet.ruby_version}}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: 'Ensure executables are installed'
        run: |
          command -v rpm || if command -v apt-get; then sudo apt-get update; sudo apt-get install -y rpm; fi ||:
          command -v rpm || { >&2 echo "FATAL: Cannot find executable: ''rpm''";  exit 1 ;}
      - name: 'Tags and changelogs'
        run: |
          bundle exec rake pkg:check_version
          bundle exec rake pkg:compare_latest_tag
          bundle exec rake pkg:create_tag_changelog
      - name: 'Validate Ruby version'
        run: 'bundle exec rake pkg:validate_ruby_version'
      - name: 'Test-build the RubyGem'
        run: 'bundle exec rake pkg:gem'

  spec-tests:
    name: 'RSpec'
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        puppet:
          - label: 'Puppet 6.18 [SIMP 6.5/PE 2019.8]'
            puppet_version: '~> 6.18.0'
            ruby_version: '2.5'
          - label: 'Puppet 5.5 [SIMP 6.4/PE 2018.1]'
            puppet_version: '~> 5.5.22'
            ruby_version: '2.4'
### simp-cli does not support Puppet 7 yet
###          - label: 'Puppet 7.x'
###            puppet_version: '~> 7.0'
###            ruby_version: '2.7'
    env:
      PUPPET_VERSION: '${{matrix.puppet.puppet_version}}'
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Ruby ${{matrix.puppet.ruby_version}}'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.puppet.ruby_version}}
          bundler-cache: true
        # simp cli code uses libpwquality or cracklib to validate passwords and
        # rsync in simp environment commands
      - run: |
          sudo apt-get update
          sudo apt-get install -y rpm cracklib-runtime libicu-dev rsync
        # simp cli code fetches USER env variable.  In the docker container USER is
        # not available, but the process is running as root.
      - run: 'USER=root SIMP_SKIP_NON_SIMPOS_TESTS=1 bundle exec rake spec'
        env:
          SKIP_COVERAGE: yes


#  dump_contexts:
#    name: 'Examine Context contents'
#    runs-on: ubuntu-16.04
#    steps:
#      - name: Dump contexts
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#
