# Build & Deploy GitHub release & RubyGem RPM when a SemVer tag is pushed
# ------------------------------------------------------------------------------
#
#             NOTICE: **This file is maintained with puppetsync**
#
# This file is updated automatically as part of a standardized asset baseline.
#
# The next baseline sync will overwrite any local changes to this file!
#
# ==============================================================================
#
# This pipeline uses the following GitHub Action Secrets:
#
#   GitHub Secret variable               Notes
#   -------------------------------      ---------------------------------------
#   SIMP_CORE_REF_FOR_BUILDING_RPMS      simp-core ref (tag) to use to build
#                                        RPMs with `rake pkg:single`
#   SIMP_DEV_GPG_SIGNING_KEY             GPG signing key's secret key
#   SIMP_DEV_GPG_SIGNING_KEY_ID          User ID (name) of signing key
#   SIMP_DEV_GPG_SIGNING_KEY_PASSPHRASE  Passphrase to use GPG signing key
#
# ------------------------------------------------------------------------------
#
# NOTES:
#
# * The CHANGLOG text is altered to remove RPM-style date headers, which don't
#   render well as markdown on the GitHub release pages
---
name: 'Tag: Release to GitHub +ibuild /attach RPMs'

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

env:
  PUPPET_VERSION: '~> 6'
  LOCAL_WORKFLOW_CONFIG_FILE: .github/workflows.local.json

jobs:
  releng-checks:
    name: "RELENG checks"
    if: github.repository_owner == 'simp'
    runs-on: ubuntu-18.04
    outputs:
      build_command: ${{ steps.commands.outputs.build_command }}
      release_command: ${{ steps.commands.outputs.release_command }}
    steps:
      - name: "Assert '${{ github.ref }}' is a tag"
        run: '[[ "$GITHUB_REF" =~ ^refs/tags/ ]] || { echo "::error ::GITHUB_REF is not a tag: ${GITHUB_REF}"; exit 1 ; }'
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
      - name: Determing build and release commands
        id: commands
        run: |
          # By default, this is the standard task from "bundler/gem_tasks"
          # To override it, add the new command to LOCAL_WORKFLOW_CONFIG_FILE
          GEM_BUILD_COMMAND='bundle exec rake build'
          if jq -r '. | keys' "$LOCAL_WORKFLOW_CONFIG_FILE" 2>/dev/null | \
              grep -w '"gem_build_command"' &> /dev/null; then
            GEM_BUILD_COMMAND="$(jq .gem_build_command "$LOCAL_WORKFLOW_CONFIG_FILE" )"
          fi
          echo "::set-output name=build_command::${GEM_BUILD_COMMAND}"
          echo "::set-output name=release_command::${GEM_RELEASE_COMMAND}"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Test build the package
        run: "${{ steps.commands.outputs.build_command }}"
      - name: "Assert '${{ github.ref }}' matches the package version"
        run: |
          tag="${GITHUB_REF/refs\/tags\//}"
          [ -f pkg/*-${tag}.gem ] || { echo "::error ::tag '${tag}' does not match package $(ls -1 pkg/*.gem)"; exit 1 ; }

  create-github-release:
    name: Deploy GitHub Release
    needs: [ releng-checks ]
    if: github.repository_owner == 'simp'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          clean: true
          fetch-depth: 0
      - name: Get tag & annotation info (${{github.ref}})
        id: tag-check
        run: |
          tag="${GITHUB_REF/refs\/tags\//}"
          annotation="$(git for-each-ref "$GITHUB_REF" --format='%(contents)' --count=1)"
          annotation_title="$(echo "$annotation" | head -1)"

          echo "::set-output name=tag::${tag}"
          echo "::set-output name=annotation_title::${annotation_title}"

          # Prepare annotation body as a file for the next step
          #
          # * The GitHub Release render the text in this file as markdown
          # * The file is needed because :set-output only supports single lines
          # * The `perl -pe` removes RPM-style date headers from the CHANGELOG,
          #   because they don't render well as markdown on the Release page
          #
          echo "$annotation" |  tail -n +2 | \
            perl -pe 'BEGIN{undef $/;} s/\n\* (Mon|Tue|Wed|Thu|Fri|Sat|Sun) .*?\n//smg;' > /tmp/annotation.body

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.tag-check.outputs.annotation_title }}
          body_path: /tmp/annotation.body
          draft: false
          prerelease: false

  build-and-attach-rpms:
    name: Trigger RPM release
    needs: [ create-github-release ]
    if: github.repository_owner == 'simp'
    runs-on: ubuntu-18.04
    env:
      TARGET_REPO: ${{ github.repository }}
    steps:
      - name: Get tag & annotation info (${{github.ref}})
        id: tag-check
        run: echo "::set-output name=tag::${GITHUB_REF/refs\/tags\//}"
      - name: Trigger RPM release workflow
        uses: actions/github-script@v4
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          TARGET_TAG: ${{ steps.tag-check.outputs.tag }}
        with:
          github-token: ${{ secrets.SIMP_AUTO_GITHUB_TOKEN__REPO_SCOPE }}
          script: |
            const [owner, repo] = process.env.TARGET_REPO.split('/')
            await github.request('POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches', {
              owner: owner,
              repo: repo,
              workflow_id: 'release_rpms.yml',
              ref: process.env.DEFAULT_BRANCH,
              inputs: {
                release_tag: process.env.TARGET_TAG
              }
            }).then( (result) => {
              console.log( `== Submitted workflow dispatch: status ${result.status}` )
            })
